version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ktv

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  mongo-data:


# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.backend
#     container_name: backend
#     restart: always
#     env_file:
#       - ./backend/.env
#     ports:
#       - 3000:3000

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile.frontend
#     container_name: frontend
#     restart: always
#     ports:
#       - 80:80
#     depends_on:
#       - backend
